// Generated by CoffeeScript 1.8.0
(function() {
  var a, b, b1, b2, createCar, extend, m, makeLightBulb, mixed, oA, oB, suv,
    __slice = [].slice;

  createCar = function(numberOfDoors) {
    var describe, numberOfWheels;
    describe = function() {
      return "I have " + numberOfWheels + " wheels and " + numberOfDoors + " doors";
    };
    numberOfWheels = 4;
    return {
      describe: describe
    };
  };

  suv = createCar(4);

  console.log(suv.describe());

  makeLightBulb = function() {
    var flip, isOn, o, status;
    isOn = true;
    flip = function() {
      return isOn = !isOn;
    };
    status = function() {
      return isOn;
    };
    o = {
      flip: flip,
      status: status
    };
    return o;
  };

  b1 = makeLightBulb();

  b2 = makeLightBulb();

  b1.flip();

  console.log("b1 is " + (b1.status()));

  console.log("b2 is " + (b2.status()));

  oA = function() {
    var a, getA;
    a = true;
    getA = function() {
      return a;
    };
    return {
      getA: getA
    };
  };

  oB = function() {
    var a, getB;
    a = false;
    getB = function() {
      return a;
    };
    return {
      getB: getB
    };
  };

  a = oA();

  b = oB();

  console.log(a.getA());

  console.log(b.getB());

  extend = function() {
    var e, extension, k, obj, v, _i, _len;
    obj = arguments[0], extension = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = extension.length; _i < _len; _i++) {
      e = extension[_i];
      for (k in e) {
        v = e[k];
        obj[k] = v;
      }
    }
    return obj;
  };

  mixed = function() {
    return extend({}, oA(), oB());
  };

  m = mixed();

  console.log("m.getA() is " + (m.getA()));

  console.log("m.getB() is " + (m.getB()));

}).call(this);
